Lesson 11: Add authorization
Bengeta/fefu_backend_23 pull request #10
Opened 2022-01-01 07:41 UTC by Bengeta

2022-01-09 10:04 UTC, chrn-feip requested changes

2022-01-09 10:04 UTC, chrn-feip commented on routes/api.php
> +Route::middleware('auth.optional')->group(function () {
Аутентификация опциональна только для действий просмотра списка и отдельной новости. Для создания, редактирования и удаления нужно её требовать. Есть разные варианты, чтобы этого достичь::
1. Почитайте про параметр only для посредника. 
2. Можно задавать посредника прямо в конструкторе контроллера, а не в группе маршрутов. 
3. Можно не задавать посредника для группы, а прописать проверку аутентификации прямо в каждом отдельном методе, который её требует.

2022-01-09 10:04 UTC, chrn-feip commented on routes/api.php
> +    Route::apiResource('posts', PostController::class)->scoped(['post' => 'slug'])->missing(function () {
Тут и в комментах тоже актуален вопрос про аутентификацию для модифицирующих методов контроллера

2022-01-10 05:02 UTC, Bengeta commented on app/Policies/NewsPolicy.php
> +        return false;
проверял

2022-01-10 12:43 UTC, chrn-feip requested changes
Пробегитесь по открытым комментам и перенесите в предыдущий PR код, который должен быть там.

2022-01-10 12:43 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        $this->middleware('auth.optional')->only('index','show');
Так на index и show одновременно накладываются auth и auth.optional. Лучше сделайте auth c only или с except. И проследите, что Auth::user() не падает или не используется (можно заменить на Auth::check()) там, где разрешено быть гостю.

2022-01-10 13:17 UTC, Bengeta commented on app/Http/Controllers/ApiAuthController.php
> +            'password' => 'required|between:10,30|regex:/^(?=(.*[A-Z]){1})(?=(.*[a-z]){1})(?=(.*[0-9]){1})(?=(.*[re@#$%^!&+=.\-_*]){1})([a-zA-Z0-9@#$%^!&+=*.\-_])*$/'
перенес

2022-01-10 13:17 UTC, Bengeta commented on app/Http/Kernel.php
> +             \Illuminate\Session\Middleware\AuthenticateSession::class,
тоже перенес

2022-01-10 14:08 UTC, Bengeta commented on app/Http/Controllers/CommentController.php
> +        $this->middleware('auth.optional')->only('index','show');
Второе условие (Auth::user()) посмотрел вроде падать не должно

2022-01-10 14:40 UTC, merged

2022-01-10 14:45 UTC, Bengeta commented
Так, извините, в первый раз пользовался интерфейсом разрешения конфликтов на гитхабе(именно здесь), случайно кликнул на commit merge,

2022-01-10 14:48 UTC, chrn-feip commented
> Так, извините, в первый раз пользовался интерфейсом разрешения конфликтов на гитхабе(именно здесь), случайно кликнул на commit merge,

Не поняла вас. Всё как будто в порядке. Мерж в мастер я самолично сделала, по горячим следам, так сказать :)

2022-01-10 14:49 UTC, chrn-feip commented
![image](https://user-images.githubusercontent.com/40585429/148785633-778c724a-e91e-40d9-960e-2daf9ca3f190.png)

на всякий случай

2022-01-10 14:50 UTC, Bengeta commented
ааа, мне показалось, что это я

2022-01-10 14:50 UTC, Bengeta commented
ладно, спасибо, и, наверное, спокойной ночи)