Lesson 12: Add Post and Comment Tests
Bengeta/fefu_backend_23 pull request #11
Opened 2022-01-15 02:30 UTC by Bengeta

2022-01-16 14:20 UTC, chrn-feip requested changes
1. Не хватает теста на удаление поста с комментами от других пользователей и поста с комментами только от автора поста.
2. Не хватает тестов на удаление автором

2022-01-16 14:20 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +       // $this->middleware('auth')->except('index','show');
Что-то меняли на время тестов и забыли вернуть? Или что-то пришлось исправлять? Никаких комментов с ненужным кодов , пожалуйста. Следите за этим. И если это была временная мера, то убедитесь, что с возвращением всего на места, тесты проходят корректно.

2022-01-16 14:20 UTC, chrn-feip commented on tests/Feature/PostTest.php
> +        $response->assertExactJson([
Код ответа тоже надо проверить

2022-01-16 14:20 UTC, chrn-feip commented on tests/Feature/CommentTest.php
> +        $response->assertExactJson([
Код ответа тоже надо проверить

2022-01-17 13:15 UTC, Bengeta commented on app/Http/Controllers/CommentController.php
> +       // $this->middleware('auth')->except('index','show');
вернул как было и проверил

2022-01-17 13:16 UTC, Bengeta commented on tests/Feature/PostTest.php
> +        $response->assertExactJson([
вставил и проверил и следующее тоже, а также добавил недостающие тесты

2022-01-17 13:25 UTC, merged